common:
  timeout: 3
  base_url: http://fecyo.fecshop.com

superhawk:
  url: https://upload.chaojiying.net/Upload/Processing.php
  username: username
  password: password
  softid: 123456
  codetype: 1004
  captcha_pic: captcha.png
